name: Docker Build And Publish image to Docker Hub

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image  
        run: |
          docker build . -t hq259/demo-1:latest 

      - name: Push Docker image to docker hub
        run: |
          docker login -u hq259 -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push hq259/demo-1:latest